### ISSUE TITLE
vocals_toy.yaml

### ISSUE THREAD

**Issue by duxuhao** [tky823/D3Net#1]
Hi tky823, thank you for sharing the pytorch version of D3Net. Would you mind sharing the vocals_toy.yamlwith us for initial testing ? Thank you!

**Comment by tky823** [comment]
See [https://github.com/tky823/DNN-based_source_separation/tree/main/egs/tutorials/d3net](https://github.com/tky823/DNN-based_source_separation/tree/main/egs/tutorials/d3net) instead (my other repository). You can test toy examples on google colab.

**Comment by duxuhao** [comment]
Gotcha, thank you!
